(function($){$.fn.tweetMachine=function(query,options,callback){$(this).each(function(){var settings,tweetMachine;if(this.tweetMachine){settings=$.extend(this.tweetMachine.settings,options);this.tweetMachine.settings=settings;if(query){this.tweetMachine.query=query}
if(this.tweetMachine.interval){this.tweetMachine.refresh()}
if(callback){this.tweetMachine.callback=callback}}else{settings=$.extend({backendScript:'ajax/getFromTwitter.php',endpoint:'search/tweets',user_name:'jason_alvis',include_retweets:!0,exclude_replies:!1,rate:5000,limit:5,autoRefresh:!0,animateOut:!1,animateIn:!0,tweetFormat:"<li><p class='content'></p><b><a href='' class='time'></a></b></li>",localization:{seconds:'seconds ago',minute:'a minute ago',minutes:'minutes ago',hour:'an hour ago',hours:'hours ago',day:'a day ago',days:'days ago'},filter:!1},options);this.tweetMachine={settings:settings,query:query,interval:!1,container:this,lastTweetID:null,callback:callback,relativeTime:function(timeString){var delta,parsedDate,r;parsedDate=Date.parse(timeString);delta=(Date.parse(Date())-parsedDate)/1000;r='';if(delta<60){r=delta+" "+settings.localization.seconds}else if(delta<120){r=settings.localization.minute}else if(delta<(45*60)){r=(parseInt(delta/60,10)).toString()+" "+settings.localization.minutes}else if(delta<(90*60)){r=settings.localization.hour}else if(delta<(24*60*60)){r=''+(parseInt(delta/3600,10)).toString()+" "+settings.localization.hours}else if(delta<(48*60*60)){r=settings.localization.day}else{r=(parseInt(delta/86400,10)).toString()+" "+settings.localization.days}
return r},updateTimestamps:function(){var tweetMachine;tweetMachine=this;$(tweetMachine.container).find('.time').each(function(){var originalTime,timeElement;timeElement=$(this);originalTime=timeElement.data('timestamp');timeElement.html(tweetMachine.relativeTime(originalTime))})},parseText:function(text){text=text.replace(/[A-Za-z]+:\/\/[A-Za-z0-9-_]+\.[A-Za-z0-9-_:%&\?\/.=]+/g,function(m){return'<a href="'+m+'" target="_blank ">'+m+'</a>'});text=text.replace(/@[A-Za-z0-9_]+/g,function(u){return'<a href="https://twitter.com/#!/'+u.replace(/^@/,'')+'" >'+u+'</a>'});text=text.replace(/#[A-Za-z0-9_\-]+/g,function(u){return'<a href="https://twitter.com/#!/search?q='+u.replace(/^#/,'%23')+'" >'+u+'</a>'});return text},buildTweet:function(tweet){var tweetMachine,tweetObj;tweetMachine=this;tweetObj=$(tweetMachine.settings.tweetFormat);tweetObj.find('.avatar').attr('src',tweet.user.profile_image_url.replace("normal","reasonably_small"));tweetObj.find('.username').attr('href',"https://twitter.com/"+tweet.user.screen_name).attr('target','_blank').html(""+tweet.user.screen_name);tweetObj.find('.time').attr('href',"https://twitter.com/"+tweet.user.screen_name+"/status/"+tweet.id_str).attr('target','_blank').html(tweetMachine.relativeTime(tweet.created_at)).data('timestamp',tweet.created_at);tweetObj.find('.content').html(tweetMachine.parseText(tweet.text));if(tweetMachine.settings.animateIn){tweetObj.css('opacity','0')}
return tweetObj},refresh:function(firstLoad){var queryParams,tweetMachine;tweetMachine=this;if(firstLoad||tweetMachine.settings.autoRefresh){if(tweetMachine.settings.endpoint==="search/tweets"){queryParams={q:tweetMachine.query,count:(this.settings.requestLimit)?this.settings.requestLimit:this.settings.limit,since_id:tweetMachine.lastTweetID}}
if(tweetMachine.settings.endpoint==="statuses/user_timeline"){queryParams={screen_name:settings.user_name,count:(this.settings.requestLimit)?this.settings.requestLimit:this.settings.limit,include_rts:settings.include_retweets,exclude_replies:settings.exclude_replies}}
$.getJSON(tweetMachine.settings.backendScript,{endpoint:tweetMachine.settings.endpoint,queryParams:queryParams},function(tweets){var tweetsDisplayed;if(tweets[0]){if(tweets[0].message){if($('.twitter-error').length){$('.twitter-error').html('<p class="tweet-machine-error">Error  '+tweets[0].code+': '+tweets[0].message+'</p>')}else{$(tweetMachine.container).before('<p class="twitter-error">Error  '+tweets[0].code+': '+tweets[0].message+'</p>')}}else{if($('.twitter-error').length){$('.twitter-error').remove()}
tweets.reverse();tweetsDisplayed=0;$.each(tweets,function(){var tweet,tweetObj;tweet=this;if(!tweetMachine.settings.filter||tweetMachine.settings.filter(this)){tweetObj=tweetMachine.buildTweet(tweet);if(!firstLoad){if(tweetMachine.settings.animateOut){}else{$(tweetMachine.container).children(':last-child').remove()}}
$(tweetMachine.container).prepend(tweetObj);if(tweetMachine.settings.animateIn){$(tweetMachine.container).children(':first-child').animate({opacity:1})}
tweetsDisplayed++;tweetMachine.lastTweetID=tweet.id_str;if(tweetsDisplayed>tweetMachine.settings.limit){return!1}}})}}
if(typeof tweetMachine.callback==="function"){if(typeof tweets==='undefined'||typeof tweetsDisplayed==='undefined'){tweets=null;tweetsDisplayed=0}
tweetMachine.callback(tweets,tweetsDisplayed)}})}},start:function(){var tweetMachine;tweetMachine=this;if(!this.interval){this.interval=setInterval(function(){tweetMachine.refresh()},tweetMachine.settings.rate);this.refresh(!0)}},stop:function(){var tweetMachine;tweetMachine=this;if(tweetMachine.interval){clearInterval(tweetMachine.interval);tweetMachine.interval=!1}},clear:function(){var tweetMachine;tweetMachine=this;$(tweetMachine.container).find('.tweet').remove();tweetMachine.lastTweetID=null}};tweetMachine=this.tweetMachine;this.timeInterval=setInterval(function(){tweetMachine.updateTimestamps()},tweetMachine.settings.rate);this.tweetMachine.start()}})}})(jQuery)